name: Publish to Permaweb

# Run workflow on every push to the master branch
on:
  push:
    branches:
      - permaweb

jobs:
  publish:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: "Set master version"
        if: ${{ github.ref == 'refs/heads/master'}}
        run: echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
        env:
          APP_VERSION: $(git rev-parse --short "$GITHUB_SHA")
      - name: "Set branch version"
        if: ${{ github.ref != 'refs/heads/master'}}
        run: echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
        env:
          APP_VERSION: ${{ env.GITHUB_REF_SLUG }}-$(git rev-parse --short "$GITHUB_SHA")
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
      - name: Build with dotnet
        run: dotnet build src/aoWebWallet --configuration Release
      - name: Publish Website
        run: dotnet publish src/aoWebWallet -o publish/aoWebWallet -c Release --version-suffix ${{ env.APP_VERSION }}
      - name: upload the directory
        uses: outlierventures/arweave-bundler@v0.3.2
        with:
          command: upload
          directory: publish/aoWebWallet/wwwroot/
          private-key: ${{secrets.ARWEAVE_PRIVATE_KEY}}
          ant-address: 'aowebwallet'
          network: arweave.net